add solution for template-lection3
js-tasks-ru/htmlcss-20220120_evgeny-labuzov pull request #11
Opened 2022-02-17 22:23 UTC by Silksofthesoul

2022-02-17 22:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-18 08:42 UTC, GSemikozov requested changes

2022-02-18 08:42 UTC, GSemikozov commented on components/page/page.css
> +.page_inner .header {
менять блок из другого блока - плохая практика, лучше использовать миксы, если в этом есть необходимость

2022-02-18 08:42 UTC, GSemikozov commented on components/page/page.css
> +.page_inner .header {
актуально и для кода ниже

2022-02-18 18:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-18 18:32 UTC, Silksofthesoul commented on components/page/page.css
> +.page_inner .header {
Исправлено.
Были добавлены классы элементы блока .page но в рамках модификатора блока .page_inner

2022-02-18 18:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-18 18:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-18 19:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-19 20:50 UTC, GSemikozov approved these changes

2022-02-19 20:50 UTC, merged