01-avatar
js-tasks-ru/htmlcss-20220120_evgeny-labuzov pull request #12
Opened 2022-02-21 20:18 UTC by Silksofthesoul

2022-02-21 20:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-22 19:54 UTC, GSemikozov requested changes

2022-02-22 19:54 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +  white-space: nowrap;
у нас ведь нет текстовых элементов внутри, можно удалить эти свойства)

2022-02-22 19:54 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +  flex-direction: row;
как и свойства для выравнивания

2022-02-22 19:54 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +  color: transparent;
отсюда и ниже - удалить (мы ведь картинку ставим через img а не через css)

2022-02-22 19:54 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar__image[alt]:after {
в контексте аватара это кажется излишеством

2022-02-22 20:16 UTC, Silksofthesoul commented on 06-lection4/01-avatar/avatar.css
> +  white-space: nowrap;
исправлено

2022-02-22 20:17 UTC, Silksofthesoul commented on 06-lection4/01-avatar/avatar.css
> +  flex-direction: row;
исправлено

2022-02-22 20:17 UTC, Silksofthesoul commented on 06-lection4/01-avatar/avatar.css
> +  color: transparent;
исправлено

2022-02-22 20:17 UTC, Silksofthesoul commented on 06-lection4/01-avatar/avatar.css
> +.avatar__image[alt]:after {
исправлено

2022-02-24 11:09 UTC, GSemikozov approved these changes, later dismissed

2022-02-24 19:28 UTC, GSemikozov approved these changes

2022-02-24 19:28 UTC, merged