add solution for 02-background-image
js-tasks-ru/htmlcss-20220120_evgeny-labuzov pull request #13
Opened 2022-02-22 19:27 UTC by Silksofthesoul

2022-02-22 19:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-22 19:55 UTC, GSemikozov requested changes

2022-02-22 19:55 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media screen and (max-width: 400px) {
это лишний медиа-запрос, по дефолту и внутри - одна и та же картинка

2022-02-22 20:18 UTC, Silksofthesoul commented on 06-lection4/02-background-image/background-image.css
> +@media screen and (max-width: 400px) {
исправлено

2022-02-24 11:10 UTC, GSemikozov approved these changes, later dismissed

2022-02-24 11:10 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-02-26 11:50 UTC, GSemikozov approved these changes

2022-02-26 11:50 UTC, merged