Lection4
js-tasks-ru/htmlcss-20220120_evgeny-labuzov pull request #15
Opened 2022-02-22 23:59 UTC by Silksofthesoul

2022-02-22 23:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-23 00:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-23 00:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-23 00:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-24 11:10 UTC, GSemikozov approved these changes, later dismissed

2022-02-24 11:10 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-02-24 17:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-24 17:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-24 17:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-24 19:29 UTC, GSemikozov requested changes

2022-02-24 19:29 UTC, GSemikozov commented on components/container/container.css
> +    padding: 1rem;
думаю сверху не надо?

2022-02-24 20:06 UTC, Silksofthesoul commented on components/container/container.css
> +    padding: 1rem;
Почему не надо? В макете я наблюдаю как отступ уменьшился до 16 пикселей в мобильной версии. 
В основной версии он был равномерным 24px, в мобильном разрешении я не вижу причин его уменьшать по разному, особенно учитывая тот факт, что блок является утилитарным, и в каком контексте будет использован не очень известно.

Сам отступ сверху (если мы к примеру рассуждаем о главной странице), задается через .cards_modif, где я учитываю, отступ контейнера 16px
```css
@media screen and (max-width: 375px) {
  .cards_modif{
    padding-top: calc(1.4375rem - 1rem);
    padding-bottom: calc(1.4375rem - 1rem);
  }
/*...*/
}
```

2022-02-24 20:10 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-26 11:50 UTC, GSemikozov commented on components/container/container.css
> +    padding: 1rem;
дело в том, что в макете нигде не указано что у общего контейнера сверху есть паддинги. Поэтому здесь если нужны паддинги - это скорее внутренние свойства других блоков, а не контейнера

2022-02-26 18:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-26 18:50 UTC, GSemikozov approved these changes

2022-02-26 18:50 UTC, merged