01 theme changer
js-tasks-ru/htmlcss-20220120_evgeny-labuzov pull request #24
Opened 2022-03-18 23:25 UTC by Silksofthesoul

2022-03-18 23:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-20 14:59 UTC, GSemikozov requested changes

2022-03-20 14:59 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +[data-theme-dark] .calendar__header {
не буду везде писать однотипные комменты, напишу только здесь.

общая однотипная ошибка)

темизацию нужно оформить таким образом, чтобы менялся лишь семантический слой переменных, причем в одном месте, там, где эти переменные определены (main.css). Будет большой ошибкой чекать тему в каждом конкретном компоненте. Наши компоненты не должны знать ничего о темизации

2022-03-20 22:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-20 22:36 UTC, Silksofthesoul commented on 05-lection3/03-calendar/calendar.css
> +[data-theme-dark] .calendar__header {
Внесены исправления. 
Файл variables.scss был немного оптимизирован и для каждого блока созданы файлы с переменными.
Тема меняется изменением переменных.

2022-03-21 08:58 UTC, GSemikozov approved these changes

2022-03-21 08:58 UTC, merged