01 button
js-tasks-ru/htmlcss-20220120_evgeny-labuzov pull request #3
Opened 2022-01-25 23:52 UTC by Silksofthesoul

add solution for 03-lection1/01-button

2022-01-25 23:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-26 23:26 UTC, GSemikozov requested changes

2022-01-26 23:26 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +body {
общие / глобальные стили (body и пр) или стили для определения других блоков (.presentation) применять в файле стилей конкретного компонента будет ошибкой - их надо унести в соответствующие места (глобальные - например в main.css, другие компоненты - создав папку с названием компонента в /components/). Если же эти стили просто вспомогательные для размещения кнопок и нигде не будут переиспользоваться - тогда их можно поместить прямо на хтмл страницу с решением в тег style

2022-01-27 23:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-27 23:41 UTC, Silksofthesoul commented on 03-lection1/01-button/button.css
> +body {
Внес изменения.
- создал компонент .presentation
- стили применяемы только в текущем решении вынес в html <style>...</style>
- вынес переменные в отдельный файл
- для пары кнопок добавил aria-.. и role
- добавил скрипт, который для кнопки primary добавляет/убирает атрибут disabled, а у secondary меняет только класс.

2022-01-28 19:19 UTC, GSemikozov approved these changes

2022-01-28 19:19 UTC, merged