01 histogram
js-tasks-ru/htmlcss-20220120_evgeny-labuzov pull request #6
Opened 2022-02-08 18:57 UTC by Silksofthesoul

2022-02-08 18:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-08 19:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-09 07:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-09 16:49 UTC, GSemikozov requested changes

2022-02-09 16:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__item {
наш компонент - это один чарт, не сетка из чартов, поэтому - переименуем .histogram__item в .histogram

2022-02-09 16:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  font-size: 1rem;
не забываем указывать font-family

2022-02-09 16:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  flex-direction: row-reverse;
а зачем reverse?)

2022-02-09 16:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  direction: rtl;
и это незачем ставить в rtl)

2022-02-09 16:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  margin-left:  1px;
это лишнее

2022-02-09 16:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  width: 100%;
пусть родитель решает какая будет ширина у детей)

2022-02-09 16:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__chart .histogram__column.histogram__column_critical {
.histogram__column.histogram__column_critical - так не нужно, можно просто модификатор писать

2022-02-09 16:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__value.histogram__value_ghost {
просто модификатор

2022-02-09 16:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__value.histogram__value_ghostAppear {
просто модификатор

2022-02-09 16:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__value.histogram__value_hide {
просто модификатор

2022-02-09 16:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  display: flex;
здесь еще важно не забыть указать фиксированную высоту, относительно которой колонки и будут заадаваться в процентах

2022-02-09 17:47 UTC, Silksofthesoul commented on 04-lection2/01-histogram/histogram.css
> +  margin-left:  1px;
Ок. Изменено. Родителю задано свойство gap: 1px;

2022-02-09 17:51 UTC, Silksofthesoul commented on 04-lection2/01-histogram/histogram.css
> +  width: 100%;
Ок. Изменено. заменено на flex-grow: 1; и justify-content: space-between; у родителя.

2022-02-09 17:52 UTC, Silksofthesoul commented on 04-lection2/01-histogram/histogram.css
> +.histogram__chart .histogram__column.histogram__column_critical {
Ок. Исправлено.

2022-02-09 17:52 UTC, Silksofthesoul commented on 04-lection2/01-histogram/histogram.css
> +.histogram__value.histogram__value_ghost {
Ок. Исправлено.

2022-02-09 17:52 UTC, Silksofthesoul commented on 04-lection2/01-histogram/histogram.css
> +.histogram__value.histogram__value_ghostAppear {
Ок. Исправлено.

2022-02-09 17:52 UTC, Silksofthesoul commented on 04-lection2/01-histogram/histogram.css
> +.histogram__value.histogram__value_hide {
Ок. Исправлено.

2022-02-09 17:53 UTC, Silksofthesoul commented on 04-lection2/01-histogram/histogram.css
> +  display: flex;
Ок. Исправлено.  у родителя задано grid-template-rows: 1fr 3.125rem; /* 1fr 50px */

2022-02-09 17:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-09 17:55 UTC, Silksofthesoul commented on 04-lection2/01-histogram/histogram.css
> +  direction: rtl;
Ок. Изменено.

2022-02-09 17:55 UTC, Silksofthesoul commented on 04-lection2/01-histogram/histogram.css
> +  flex-direction: row-reverse;
Ок. Изменено.

2022-02-09 17:55 UTC, Silksofthesoul commented on 04-lection2/01-histogram/histogram.css
> +  font-size: 1rem;
Ок. Исправлено.

2022-02-09 17:56 UTC, Silksofthesoul commented on 04-lection2/01-histogram/histogram.css
> +.histogram__item {
Ок. Исправлено.

2022-02-09 18:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-10 14:28 UTC, GSemikozov approved these changes

2022-02-10 14:28 UTC, merged